controller_joint_names: ['', 'joint-l1', 'joint-l2', 'joint-l3', 'joint-l4', 'joint-l5', 'joint-l6', 'joint-l7', 'joint-r1', 'joint-r2', 'joint-r3', 'joint-r4', 'joint-r5', 'joint-r6', 'joint-r7', ]
